name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Нужно для определения измененных пакетов

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint affected packages
        run: pnpm turbo run lint --filter=...[origin/main]

      - name: Type Check affected packages
        run: pnpm turbo run typecheck --filter=...[origin/main]

      - name: Test affected packages
        run: pnpm turbo run test --filter=...[origin/main]

      - name: Build affected packages
        run: pnpm turbo run build --filter=...[origin/main]